import Foundation

enum EmojiDatabase {
    // Generated from Unicode emoji-test.txt 17.0 (2025-08-04, 20:55:31 GMT).
    // Includes fully-qualified RGI emoji, excluding non-default skin-tone variants.
    static let all: [Emoji] = rawData.split(separator: "\n").map { row in
        let fields = row.split(separator: "\t", omittingEmptySubsequences: false)
        return Emoji(
            symbol: String(fields[0]),
            shortcode: String(fields[1]),
            tags: fields[2].split(separator: ",").map(String.init)
        )
    }

    private static let rawData = """
        😀	grinning_face	grinning,face
        😃	grinning_face_with_big_eyes	grinning,face,with,big,eyes
        😄	grinning_face_with_smiling_eyes	grinning,face,with,smiling,eyes
        😁	beaming_face_with_smiling_eyes	beaming,face,with,smiling,eyes
        😆	grinning_squinting_face	grinning,squinting,face
        😅	grinning_face_with_sweat	grinning,face,with,sweat
        🤣	rolling_on_the_floor_laughing	rolling,on,the,floor,laughing
        😂	face_with_tears_of_joy	face,with,tears,of,joy
        🙂	slightly_smiling_face	slightly,smiling,face
        🙃	upside_down_face	upside,down,face
        🫠	melting_face	melting,face
        😉	winking_face	winking,face
        😊	smiling_face_with_smiling_eyes	smiling,face,with,eyes
        😇	smiling_face_with_halo	smiling,face,with,halo
        🥰	smiling_face_with_hearts	smiling,face,with,hearts
        😍	smiling_face_with_heart_eyes	smiling,face,with,heart,eyes
        🤩	star_struck	star,struck
        😘	face_blowing_a_kiss	face,blowing,a,kiss
        😗	kissing_face	kissing,face
        ☺️	smiling_face	smiling,face
        😚	kissing_face_with_closed_eyes	kissing,face,with,closed,eyes
        😙	kissing_face_with_smiling_eyes	kissing,face,with,smiling,eyes
        🥲	smiling_face_with_tear	smiling,face,with,tear
        😋	face_savoring_food	face,savoring,food
        😛	face_with_tongue	face,with,tongue
        😜	winking_face_with_tongue	winking,face,with,tongue
        🤪	zany_face	zany,face
        😝	squinting_face_with_tongue	squinting,face,with,tongue
        🤑	money_mouth_face	money,mouth,face
        🤗	smiling_face_with_open_hands	smiling,face,with,open,hands
        🤭	face_with_hand_over_mouth	face,with,hand,over,mouth
        🫢	face_with_open_eyes_and_hand_over_mouth	face,with,open,eyes,and,hand,over,mouth
        🫣	face_with_peeking_eye	face,with,peeking,eye
        🤫	shushing_face	shushing,face
        🤔	thinking_face	thinking,face
        🫡	saluting_face	saluting,face
        🤐	zipper_mouth_face	zipper,mouth,face
        🤨	face_with_raised_eyebrow	face,with,raised,eyebrow
        😐	neutral_face	neutral,face
        😑	expressionless_face	expressionless,face
        😶	face_without_mouth	face,without,mouth
        🫥	dotted_line_face	dotted,line,face
        😶‍🌫️	face_in_clouds	face,in,clouds
        😏	smirking_face	smirking,face
        😒	unamused_face	unamused,face
        🙄	face_with_rolling_eyes	face,with,rolling,eyes
        😬	grimacing_face	grimacing,face
        😮‍💨	face_exhaling	face,exhaling
        🤥	lying_face	lying,face
        🫨	shaking_face	shaking,face
        🙂‍↔️	head_shaking_horizontally	head,shaking,horizontally
        🙂‍↕️	head_shaking_vertically	head,shaking,vertically
        😌	relieved_face	relieved,face
        😔	pensive_face	pensive,face
        😪	sleepy_face	sleepy,face
        🤤	drooling_face	drooling,face
        😴	sleeping_face	sleeping,face
        🫩	face_with_bags_under_eyes	face,with,bags,under,eyes
        😷	face_with_medical_mask	face,with,medical,mask
        🤒	face_with_thermometer	face,with,thermometer
        🤕	face_with_head_bandage	face,with,head,bandage
        🤢	nauseated_face	nauseated,face
        🤮	face_vomiting	face,vomiting
        🤧	sneezing_face	sneezing,face
        🥵	hot_face	hot,face
        🥶	cold_face	cold,face
        🥴	woozy_face	woozy,face
        😵	face_with_crossed_out_eyes	face,with,crossed,out,eyes
        😵‍💫	face_with_spiral_eyes	face,with,spiral,eyes
        🤯	exploding_head	exploding,head
        🤠	cowboy_hat_face	cowboy,hat,face
        🥳	partying_face	partying,face
        🥸	disguised_face	disguised,face
        😎	smiling_face_with_sunglasses	smiling,face,with,sunglasses
        🤓	nerd_face	nerd,face
        🧐	face_with_monocle	face,with,monocle
        😕	confused_face	confused,face
        🫤	face_with_diagonal_mouth	face,with,diagonal,mouth
        😟	worried_face	worried,face
        🙁	slightly_frowning_face	slightly,frowning,face
        ☹️	frowning_face	frowning,face
        😮	face_with_open_mouth	face,with,open,mouth
        😯	hushed_face	hushed,face
        😲	astonished_face	astonished,face
        😳	flushed_face	flushed,face
        🫪	distorted_face	distorted,face
        🥺	pleading_face	pleading,face
        🥹	face_holding_back_tears	face,holding,back,tears
        😦	frowning_face_with_open_mouth	frowning,face,with,open,mouth
        😧	anguished_face	anguished,face
        😨	fearful_face	fearful,face
        😰	anxious_face_with_sweat	anxious,face,with,sweat
        😥	sad_but_relieved_face	sad,but,relieved,face
        😢	crying_face	crying,face
        😭	loudly_crying_face	loudly,crying,face
        😱	face_screaming_in_fear	face,screaming,in,fear
        😖	confounded_face	confounded,face
        😣	persevering_face	persevering,face
        😞	disappointed_face	disappointed,face
        😓	downcast_face_with_sweat	downcast,face,with,sweat
        😩	weary_face	weary,face
        😫	tired_face	tired,face
        🥱	yawning_face	yawning,face
        😤	face_with_steam_from_nose	face,with,steam,from,nose
        😡	enraged_face	enraged,face
        😠	angry_face	angry,face
        🤬	face_with_symbols_on_mouth	face,with,symbols,on,mouth
        😈	smiling_face_with_horns	smiling,face,with,horns
        👿	angry_face_with_horns	angry,face,with,horns
        💀	skull	skull
        ☠️	skull_and_crossbones	skull,and,crossbones
        💩	pile_of_poo	pile,of,poo
        🤡	clown_face	clown,face
        👹	ogre	ogre
        👺	goblin	goblin
        👻	ghost	ghost
        👽	alien	alien
        👾	alien_monster	alien,monster
        🤖	robot	robot
        😺	grinning_cat	grinning,cat
        😸	grinning_cat_with_smiling_eyes	grinning,cat,with,smiling,eyes
        😹	cat_with_tears_of_joy	cat,with,tears,of,joy
        😻	smiling_cat_with_heart_eyes	smiling,cat,with,heart,eyes
        😼	cat_with_wry_smile	cat,with,wry,smile
        😽	kissing_cat	kissing,cat
        🙀	weary_cat	weary,cat
        😿	crying_cat	crying,cat
        😾	pouting_cat	pouting,cat
        🙈	see_no_evil_monkey	see,no,evil,monkey
        🙉	hear_no_evil_monkey	hear,no,evil,monkey
        🙊	speak_no_evil_monkey	speak,no,evil,monkey
        💌	love_letter	love,letter
        💘	heart_with_arrow	heart,with,arrow
        💝	heart_with_ribbon	heart,with,ribbon
        💖	sparkling_heart	sparkling,heart
        💗	growing_heart	growing,heart
        💓	beating_heart	beating,heart
        💞	revolving_hearts	revolving,hearts
        💕	two_hearts	two,hearts
        💟	heart_decoration	heart,decoration
        ❣️	heart_exclamation	heart,exclamation
        💔	broken_heart	broken,heart
        ❤️‍🔥	heart_on_fire	heart,on,fire
        ❤️‍🩹	mending_heart	mending,heart
        ❤️	red_heart	red,heart
        🩷	pink_heart	pink,heart
        🧡	orange_heart	orange,heart
        💛	yellow_heart	yellow,heart
        💚	green_heart	green,heart
        💙	blue_heart	blue,heart
        🩵	light_blue_heart	light,blue,heart
        💜	purple_heart	purple,heart
        🤎	brown_heart	brown,heart
        🖤	black_heart	black,heart
        🩶	grey_heart	grey,heart
        🤍	white_heart	white,heart
        💋	kiss_mark	kiss,mark
        💯	hundred_points	hundred,points
        💢	anger_symbol	anger,symbol
        🫯	fight_cloud	fight,cloud
        💥	collision	collision
        💫	dizzy	dizzy
        💦	sweat_droplets	sweat,droplets
        💨	dashing_away	dashing,away
        🕳️	hole	hole
        💬	speech_balloon	speech,balloon
        👁️‍🗨️	eye_in_speech_bubble	eye,in,speech,bubble
        🗨️	left_speech_bubble	left,speech,bubble
        🗯️	right_anger_bubble	right,anger,bubble
        💭	thought_balloon	thought,balloon
        💤	zzz	zzz
        👋	waving_hand	waving,hand
        🤚	raised_back_of_hand	raised,back,of,hand
        🖐️	hand_with_fingers_splayed	hand,with,fingers,splayed
        ✋	raised_hand	raised,hand
        🖖	vulcan_salute	vulcan,salute
        🫱	rightwards_hand	rightwards,hand
        🫲	leftwards_hand	leftwards,hand
        🫳	palm_down_hand	palm,down,hand
        🫴	palm_up_hand	palm,up,hand
        🫷	leftwards_pushing_hand	leftwards,pushing,hand
        🫸	rightwards_pushing_hand	rightwards,pushing,hand
        👌	ok_hand	ok,hand
        🤌	pinched_fingers	pinched,fingers
        🤏	pinching_hand	pinching,hand
        ✌️	victory_hand	victory,hand
        🤞	crossed_fingers	crossed,fingers
        🫰	hand_with_index_finger_and_thumb_crossed	hand,with,index,finger,and,thumb,crossed
        🤟	love_you_gesture	love,you,gesture
        🤘	sign_of_the_horns	sign,of,the,horns
        🤙	call_me_hand	call,me,hand
        👈	backhand_index_pointing_left	backhand,index,pointing,left
        👉	backhand_index_pointing_right	backhand,index,pointing,right
        👆	backhand_index_pointing_up	backhand,index,pointing,up
        🖕	middle_finger	middle,finger
        👇	backhand_index_pointing_down	backhand,index,pointing,down
        ☝️	index_pointing_up	index,pointing,up
        🫵	index_pointing_at_the_viewer	index,pointing,at,the,viewer
        👍	thumbs_up	thumbs,up
        👎	thumbs_down	thumbs,down
        ✊	raised_fist	raised,fist
        👊	oncoming_fist	oncoming,fist
        🤛	left_facing_fist	left,facing,fist
        🤜	right_facing_fist	right,facing,fist
        👏	clapping_hands	clapping,hands
        🙌	raising_hands	raising,hands
        🫶	heart_hands	heart,hands
        👐	open_hands	open,hands
        🤲	palms_up_together	palms,up,together
        🤝	handshake	handshake
        🙏	folded_hands	folded,hands
        ✍️	writing_hand	writing,hand
        💅	nail_polish	nail,polish
        🤳	selfie	selfie
        💪	flexed_biceps	flexed,biceps
        🦾	mechanical_arm	mechanical,arm
        🦿	mechanical_leg	mechanical,leg
        🦵	leg	leg
        🦶	foot	foot
        👂	ear	ear
        🦻	ear_with_hearing_aid	ear,with,hearing,aid
        👃	nose	nose
        🧠	brain	brain
        🫀	anatomical_heart	anatomical,heart
        🫁	lungs	lungs
        🦷	tooth	tooth
        🦴	bone	bone
        👀	eyes	eyes
        👁️	eye	eye
        👅	tongue	tongue
        👄	mouth	mouth
        🫦	biting_lip	biting,lip
        👶	baby	baby
        🧒	child	child
        👦	boy	boy
        👧	girl	girl
        🧑	person	person
        👱	person_blond_hair	person,blond,hair
        👨	man	man
        🧔	person_beard	person,beard
        🧔‍♂️	man_beard	man,beard
        🧔‍♀️	woman_beard	woman,beard
        👨‍🦰	man_red_hair	man,red,hair
        👨‍🦱	man_curly_hair	man,curly,hair
        👨‍🦳	man_white_hair	man,white,hair
        👨‍🦲	man_bald	man,bald
        👩	woman	woman
        👩‍🦰	woman_red_hair	woman,red,hair
        🧑‍🦰	person_red_hair	person,red,hair
        👩‍🦱	woman_curly_hair	woman,curly,hair
        🧑‍🦱	person_curly_hair	person,curly,hair
        👩‍🦳	woman_white_hair	woman,white,hair
        🧑‍🦳	person_white_hair	person,white,hair
        👩‍🦲	woman_bald	woman,bald
        🧑‍🦲	person_bald	person,bald
        👱‍♀️	woman_blond_hair	woman,blond,hair
        👱‍♂️	man_blond_hair	man,blond,hair
        🧓	older_person	older,person
        👴	old_man	old,man
        👵	old_woman	old,woman
        🙍	person_frowning	person,frowning
        🙍‍♂️	man_frowning	man,frowning
        🙍‍♀️	woman_frowning	woman,frowning
        🙎	person_pouting	person,pouting
        🙎‍♂️	man_pouting	man,pouting
        🙎‍♀️	woman_pouting	woman,pouting
        🙅	person_gesturing_no	person,gesturing,no
        🙅‍♂️	man_gesturing_no	man,gesturing,no
        🙅‍♀️	woman_gesturing_no	woman,gesturing,no
        🙆	person_gesturing_ok	person,gesturing,ok
        🙆‍♂️	man_gesturing_ok	man,gesturing,ok
        🙆‍♀️	woman_gesturing_ok	woman,gesturing,ok
        💁	person_tipping_hand	person,tipping,hand
        💁‍♂️	man_tipping_hand	man,tipping,hand
        💁‍♀️	woman_tipping_hand	woman,tipping,hand
        🙋	person_raising_hand	person,raising,hand
        🙋‍♂️	man_raising_hand	man,raising,hand
        🙋‍♀️	woman_raising_hand	woman,raising,hand
        🧏	deaf_person	deaf,person
        🧏‍♂️	deaf_man	deaf,man
        🧏‍♀️	deaf_woman	deaf,woman
        🙇	person_bowing	person,bowing
        🙇‍♂️	man_bowing	man,bowing
        🙇‍♀️	woman_bowing	woman,bowing
        🤦	person_facepalming	person,facepalming
        🤦‍♂️	man_facepalming	man,facepalming
        🤦‍♀️	woman_facepalming	woman,facepalming
        🤷	person_shrugging	person,shrugging
        🤷‍♂️	man_shrugging	man,shrugging
        🤷‍♀️	woman_shrugging	woman,shrugging
        🧑‍⚕️	health_worker	health,worker
        👨‍⚕️	man_health_worker	man,health,worker
        👩‍⚕️	woman_health_worker	woman,health,worker
        🧑‍🎓	student	student
        👨‍🎓	man_student	man,student
        👩‍🎓	woman_student	woman,student
        🧑‍🏫	teacher	teacher
        👨‍🏫	man_teacher	man,teacher
        👩‍🏫	woman_teacher	woman,teacher
        🧑‍⚖️	judge	judge
        👨‍⚖️	man_judge	man,judge
        👩‍⚖️	woman_judge	woman,judge
        🧑‍🌾	farmer	farmer
        👨‍🌾	man_farmer	man,farmer
        👩‍🌾	woman_farmer	woman,farmer
        🧑‍🍳	cook	cook
        👨‍🍳	man_cook	man,cook
        👩‍🍳	woman_cook	woman,cook
        🧑‍🔧	mechanic	mechanic
        👨‍🔧	man_mechanic	man,mechanic
        👩‍🔧	woman_mechanic	woman,mechanic
        🧑‍🏭	factory_worker	factory,worker
        👨‍🏭	man_factory_worker	man,factory,worker
        👩‍🏭	woman_factory_worker	woman,factory,worker
        🧑‍💼	office_worker	office,worker
        👨‍💼	man_office_worker	man,office,worker
        👩‍💼	woman_office_worker	woman,office,worker
        🧑‍🔬	scientist	scientist
        👨‍🔬	man_scientist	man,scientist
        👩‍🔬	woman_scientist	woman,scientist
        🧑‍💻	technologist	technologist
        👨‍💻	man_technologist	man,technologist
        👩‍💻	woman_technologist	woman,technologist
        🧑‍🎤	singer	singer
        👨‍🎤	man_singer	man,singer
        👩‍🎤	woman_singer	woman,singer
        🧑‍🎨	artist	artist
        👨‍🎨	man_artist	man,artist
        👩‍🎨	woman_artist	woman,artist
        🧑‍✈️	pilot	pilot
        👨‍✈️	man_pilot	man,pilot
        👩‍✈️	woman_pilot	woman,pilot
        🧑‍🚀	astronaut	astronaut
        👨‍🚀	man_astronaut	man,astronaut
        👩‍🚀	woman_astronaut	woman,astronaut
        🧑‍🚒	firefighter	firefighter
        👨‍🚒	man_firefighter	man,firefighter
        👩‍🚒	woman_firefighter	woman,firefighter
        👮	police_officer	police,officer
        👮‍♂️	man_police_officer	man,police,officer
        👮‍♀️	woman_police_officer	woman,police,officer
        🕵️	detective	detective
        🕵️‍♂️	man_detective	man,detective
        🕵️‍♀️	woman_detective	woman,detective
        💂	guard	guard
        💂‍♂️	man_guard	man,guard
        💂‍♀️	woman_guard	woman,guard
        🥷	ninja	ninja
        👷	construction_worker	construction,worker
        👷‍♂️	man_construction_worker	man,construction,worker
        👷‍♀️	woman_construction_worker	woman,construction,worker
        🫅	person_with_crown	person,with,crown
        🤴	prince	prince
        👸	princess	princess
        👳	person_wearing_turban	person,wearing,turban
        👳‍♂️	man_wearing_turban	man,wearing,turban
        👳‍♀️	woman_wearing_turban	woman,wearing,turban
        👲	person_with_skullcap	person,with,skullcap
        🧕	woman_with_headscarf	woman,with,headscarf
        🤵	person_in_tuxedo	person,in,tuxedo
        🤵‍♂️	man_in_tuxedo	man,in,tuxedo
        🤵‍♀️	woman_in_tuxedo	woman,in,tuxedo
        👰	person_with_veil	person,with,veil
        👰‍♂️	man_with_veil	man,with,veil
        👰‍♀️	woman_with_veil	woman,with,veil
        🤰	pregnant_woman	pregnant,woman
        🫃	pregnant_man	pregnant,man
        🫄	pregnant_person	pregnant,person
        🤱	breast_feeding	breast,feeding
        👩‍🍼	woman_feeding_baby	woman,feeding,baby
        👨‍🍼	man_feeding_baby	man,feeding,baby
        🧑‍🍼	person_feeding_baby	person,feeding,baby
        👼	baby_angel	baby,angel
        🎅	santa_claus	santa,claus
        🤶	mrs_claus	mrs,claus
        🧑‍🎄	mx_claus	mx,claus
        🦸	superhero	superhero
        🦸‍♂️	man_superhero	man,superhero
        🦸‍♀️	woman_superhero	woman,superhero
        🦹	supervillain	supervillain
        🦹‍♂️	man_supervillain	man,supervillain
        🦹‍♀️	woman_supervillain	woman,supervillain
        🧙	mage	mage
        🧙‍♂️	man_mage	man,mage
        🧙‍♀️	woman_mage	woman,mage
        🧚	fairy	fairy
        🧚‍♂️	man_fairy	man,fairy
        🧚‍♀️	woman_fairy	woman,fairy
        🧛	vampire	vampire
        🧛‍♂️	man_vampire	man,vampire
        🧛‍♀️	woman_vampire	woman,vampire
        🧜	merperson	merperson
        🧜‍♂️	merman	merman
        🧜‍♀️	mermaid	mermaid
        🧝	elf	elf
        🧝‍♂️	man_elf	man,elf
        🧝‍♀️	woman_elf	woman,elf
        🧞	genie	genie
        🧞‍♂️	man_genie	man,genie
        🧞‍♀️	woman_genie	woman,genie
        🧟	zombie	zombie
        🧟‍♂️	man_zombie	man,zombie
        🧟‍♀️	woman_zombie	woman,zombie
        🧌	troll	troll
        🫈	hairy_creature	hairy,creature
        💆	person_getting_massage	person,getting,massage
        💆‍♂️	man_getting_massage	man,getting,massage
        💆‍♀️	woman_getting_massage	woman,getting,massage
        💇	person_getting_haircut	person,getting,haircut
        💇‍♂️	man_getting_haircut	man,getting,haircut
        💇‍♀️	woman_getting_haircut	woman,getting,haircut
        🚶	person_walking	person,walking
        🚶‍♂️	man_walking	man,walking
        🚶‍♀️	woman_walking	woman,walking
        🚶‍➡️	person_walking_facing_right	person,walking,facing,right
        🚶‍♀️‍➡️	woman_walking_facing_right	woman,walking,facing,right
        🚶‍♂️‍➡️	man_walking_facing_right	man,walking,facing,right
        🧍	person_standing	person,standing
        🧍‍♂️	man_standing	man,standing
        🧍‍♀️	woman_standing	woman,standing
        🧎	person_kneeling	person,kneeling
        🧎‍♂️	man_kneeling	man,kneeling
        🧎‍♀️	woman_kneeling	woman,kneeling
        🧎‍➡️	person_kneeling_facing_right	person,kneeling,facing,right
        🧎‍♀️‍➡️	woman_kneeling_facing_right	woman,kneeling,facing,right
        🧎‍♂️‍➡️	man_kneeling_facing_right	man,kneeling,facing,right
        🧑‍🦯	person_with_white_cane	person,with,white,cane
        🧑‍🦯‍➡️	person_with_white_cane_facing_right	person,with,white,cane,facing,right
        👨‍🦯	man_with_white_cane	man,with,white,cane
        👨‍🦯‍➡️	man_with_white_cane_facing_right	man,with,white,cane,facing,right
        👩‍🦯	woman_with_white_cane	woman,with,white,cane
        👩‍🦯‍➡️	woman_with_white_cane_facing_right	woman,with,white,cane,facing,right
        🧑‍🦼	person_in_motorized_wheelchair	person,in,motorized,wheelchair
        🧑‍🦼‍➡️	person_in_motorized_wheelchair_facing_right	person,in,motorized,wheelchair,facing,right
        👨‍🦼	man_in_motorized_wheelchair	man,in,motorized,wheelchair
        👨‍🦼‍➡️	man_in_motorized_wheelchair_facing_right	man,in,motorized,wheelchair,facing,right
        👩‍🦼	woman_in_motorized_wheelchair	woman,in,motorized,wheelchair
        👩‍🦼‍➡️	woman_in_motorized_wheelchair_facing_right	woman,in,motorized,wheelchair,facing,right
        🧑‍🦽	person_in_manual_wheelchair	person,in,manual,wheelchair
        🧑‍🦽‍➡️	person_in_manual_wheelchair_facing_right	person,in,manual,wheelchair,facing,right
        👨‍🦽	man_in_manual_wheelchair	man,in,manual,wheelchair
        👨‍🦽‍➡️	man_in_manual_wheelchair_facing_right	man,in,manual,wheelchair,facing,right
        👩‍🦽	woman_in_manual_wheelchair	woman,in,manual,wheelchair
        👩‍🦽‍➡️	woman_in_manual_wheelchair_facing_right	woman,in,manual,wheelchair,facing,right
        🏃	person_running	person,running
        🏃‍♂️	man_running	man,running
        🏃‍♀️	woman_running	woman,running
        🏃‍➡️	person_running_facing_right	person,running,facing,right
        🏃‍♀️‍➡️	woman_running_facing_right	woman,running,facing,right
        🏃‍♂️‍➡️	man_running_facing_right	man,running,facing,right
        🧑‍🩰	ballet_dancer	ballet,dancer
        💃	woman_dancing	woman,dancing
        🕺	man_dancing	man,dancing
        🕴️	person_in_suit_levitating	person,in,suit,levitating
        👯	people_with_bunny_ears	people,with,bunny,ears
        👯‍♂️	men_with_bunny_ears	men,with,bunny,ears
        👯‍♀️	women_with_bunny_ears	women,with,bunny,ears
        🧖	person_in_steamy_room	person,in,steamy,room
        🧖‍♂️	man_in_steamy_room	man,in,steamy,room
        🧖‍♀️	woman_in_steamy_room	woman,in,steamy,room
        🧗	person_climbing	person,climbing
        🧗‍♂️	man_climbing	man,climbing
        🧗‍♀️	woman_climbing	woman,climbing
        🤺	person_fencing	person,fencing
        🏇	horse_racing	horse,racing
        ⛷️	skier	skier
        🏂	snowboarder	snowboarder
        🏌️	person_golfing	person,golfing
        🏌️‍♂️	man_golfing	man,golfing
        🏌️‍♀️	woman_golfing	woman,golfing
        🏄	person_surfing	person,surfing
        🏄‍♂️	man_surfing	man,surfing
        🏄‍♀️	woman_surfing	woman,surfing
        🚣	person_rowing_boat	person,rowing,boat
        🚣‍♂️	man_rowing_boat	man,rowing,boat
        🚣‍♀️	woman_rowing_boat	woman,rowing,boat
        🏊	person_swimming	person,swimming
        🏊‍♂️	man_swimming	man,swimming
        🏊‍♀️	woman_swimming	woman,swimming
        ⛹️	person_bouncing_ball	person,bouncing,ball
        ⛹️‍♂️	man_bouncing_ball	man,bouncing,ball
        ⛹️‍♀️	woman_bouncing_ball	woman,bouncing,ball
        🏋️	person_lifting_weights	person,lifting,weights
        🏋️‍♂️	man_lifting_weights	man,lifting,weights
        🏋️‍♀️	woman_lifting_weights	woman,lifting,weights
        🚴	person_biking	person,biking
        🚴‍♂️	man_biking	man,biking
        🚴‍♀️	woman_biking	woman,biking
        🚵	person_mountain_biking	person,mountain,biking
        🚵‍♂️	man_mountain_biking	man,mountain,biking
        🚵‍♀️	woman_mountain_biking	woman,mountain,biking
        🤸	person_cartwheeling	person,cartwheeling
        🤸‍♂️	man_cartwheeling	man,cartwheeling
        🤸‍♀️	woman_cartwheeling	woman,cartwheeling
        🤼	people_wrestling	people,wrestling
        🤼‍♂️	men_wrestling	men,wrestling
        🤼‍♀️	women_wrestling	women,wrestling
        🤽	person_playing_water_polo	person,playing,water,polo
        🤽‍♂️	man_playing_water_polo	man,playing,water,polo
        🤽‍♀️	woman_playing_water_polo	woman,playing,water,polo
        🤾	person_playing_handball	person,playing,handball
        🤾‍♂️	man_playing_handball	man,playing,handball
        🤾‍♀️	woman_playing_handball	woman,playing,handball
        🤹	person_juggling	person,juggling
        🤹‍♂️	man_juggling	man,juggling
        🤹‍♀️	woman_juggling	woman,juggling
        🧘	person_in_lotus_position	person,in,lotus,position
        🧘‍♂️	man_in_lotus_position	man,in,lotus,position
        🧘‍♀️	woman_in_lotus_position	woman,in,lotus,position
        🛀	person_taking_bath	person,taking,bath
        🛌	person_in_bed	person,in,bed
        🧑‍🤝‍🧑	people_holding_hands	people,holding,hands
        👭	women_holding_hands	women,holding,hands
        👫	woman_and_man_holding_hands	woman,and,man,holding,hands
        👬	men_holding_hands	men,holding,hands
        💏	kiss	kiss
        👩‍❤️‍💋‍👨	kiss_woman_man	kiss,woman,man
        👨‍❤️‍💋‍👨	kiss_man_man	kiss,man
        👩‍❤️‍💋‍👩	kiss_woman_woman	kiss,woman
        💑	couple_with_heart	couple,with,heart
        👩‍❤️‍👨	couple_with_heart_woman_man	couple,with,heart,woman,man
        👨‍❤️‍👨	couple_with_heart_man_man	couple,with,heart,man
        👩‍❤️‍👩	couple_with_heart_woman_woman	couple,with,heart,woman
        👨‍👩‍👦	family_man_woman_boy	family,man,woman,boy
        👨‍👩‍👧	family_man_woman_girl	family,man,woman,girl
        👨‍👩‍👧‍👦	family_man_woman_girl_boy	family,man,woman,girl,boy
        👨‍👩‍👦‍👦	family_man_woman_boy_boy	family,man,woman,boy
        👨‍👩‍👧‍👧	family_man_woman_girl_girl	family,man,woman,girl
        👨‍👨‍👦	family_man_man_boy	family,man,boy
        👨‍👨‍👧	family_man_man_girl	family,man,girl
        👨‍👨‍👧‍👦	family_man_man_girl_boy	family,man,girl,boy
        👨‍👨‍👦‍👦	family_man_man_boy_boy	family,man,boy
        👨‍👨‍👧‍👧	family_man_man_girl_girl	family,man,girl
        👩‍👩‍👦	family_woman_woman_boy	family,woman,boy
        👩‍👩‍👧	family_woman_woman_girl	family,woman,girl
        👩‍👩‍👧‍👦	family_woman_woman_girl_boy	family,woman,girl,boy
        👩‍👩‍👦‍👦	family_woman_woman_boy_boy	family,woman,boy
        👩‍👩‍👧‍👧	family_woman_woman_girl_girl	family,woman,girl
        👨‍👦	family_man_boy	family,man,boy
        👨‍👦‍👦	family_man_boy_boy	family,man,boy
        👨‍👧	family_man_girl	family,man,girl
        👨‍👧‍👦	family_man_girl_boy	family,man,girl,boy
        👨‍👧‍👧	family_man_girl_girl	family,man,girl
        👩‍👦	family_woman_boy	family,woman,boy
        👩‍👦‍👦	family_woman_boy_boy	family,woman,boy
        👩‍👧	family_woman_girl	family,woman,girl
        👩‍👧‍👦	family_woman_girl_boy	family,woman,girl,boy
        👩‍👧‍👧	family_woman_girl_girl	family,woman,girl
        🗣️	speaking_head	speaking,head
        👤	bust_in_silhouette	bust,in,silhouette
        👥	busts_in_silhouette	busts,in,silhouette
        🫂	people_hugging	people,hugging
        👪	family	family
        🧑‍🧑‍🧒	family_adult_adult_child	family,adult,child
        🧑‍🧑‍🧒‍🧒	family_adult_adult_child_child	family,adult,child
        🧑‍🧒	family_adult_child	family,adult,child
        🧑‍🧒‍🧒	family_adult_child_child	family,adult,child
        👣	footprints	footprints
        🫆	fingerprint	fingerprint
        🐵	monkey_face	monkey,face
        🐒	monkey	monkey
        🦍	gorilla	gorilla
        🦧	orangutan	orangutan
        🐶	dog_face	dog,face
        🐕	dog	dog
        🦮	guide_dog	guide,dog
        🐕‍🦺	service_dog	service,dog
        🐩	poodle	poodle
        🐺	wolf	wolf
        🦊	fox	fox
        🦝	raccoon	raccoon
        🐱	cat_face	cat,face
        🐈	cat	cat
        🐈‍⬛	black_cat	black,cat
        🦁	lion	lion
        🐯	tiger_face	tiger,face
        🐅	tiger	tiger
        🐆	leopard	leopard
        🐴	horse_face	horse,face
        🫎	moose	moose
        🫏	donkey	donkey
        🐎	horse	horse
        🦄	unicorn	unicorn
        🦓	zebra	zebra
        🦌	deer	deer
        🦬	bison	bison
        🐮	cow_face	cow,face
        🐂	ox	ox
        🐃	water_buffalo	water,buffalo
        🐄	cow	cow
        🐷	pig_face	pig,face
        🐖	pig	pig
        🐗	boar	boar
        🐽	pig_nose	pig,nose
        🐏	ram	ram
        🐑	ewe	ewe
        🐐	goat	goat
        🐪	camel	camel
        🐫	two_hump_camel	two,hump,camel
        🦙	llama	llama
        🦒	giraffe	giraffe
        🐘	elephant	elephant
        🦣	mammoth	mammoth
        🦏	rhinoceros	rhinoceros
        🦛	hippopotamus	hippopotamus
        🐭	mouse_face	mouse,face
        🐁	mouse	mouse
        🐀	rat	rat
        🐹	hamster	hamster
        🐰	rabbit_face	rabbit,face
        🐇	rabbit	rabbit
        🐿️	chipmunk	chipmunk
        🦫	beaver	beaver
        🦔	hedgehog	hedgehog
        🦇	bat	bat
        🐻	bear	bear
        🐻‍❄️	polar_bear	polar,bear
        🐨	koala	koala
        🐼	panda	panda
        🦥	sloth	sloth
        🦦	otter	otter
        🦨	skunk	skunk
        🦘	kangaroo	kangaroo
        🦡	badger	badger
        🐾	paw_prints	paw,prints
        🦃	turkey	turkey
        🐔	chicken	chicken
        🐓	rooster	rooster
        🐣	hatching_chick	hatching,chick
        🐤	baby_chick	baby,chick
        🐥	front_facing_baby_chick	front,facing,baby,chick
        🐦	bird	bird
        🐧	penguin	penguin
        🕊️	dove	dove
        🦅	eagle	eagle
        🦆	duck	duck
        🦢	swan	swan
        🦉	owl	owl
        🦤	dodo	dodo
        🪶	feather	feather
        🦩	flamingo	flamingo
        🦚	peacock	peacock
        🦜	parrot	parrot
        🪽	wing	wing
        🐦‍⬛	black_bird	black,bird
        🪿	goose	goose
        🐦‍🔥	phoenix	phoenix
        🐸	frog	frog
        🐊	crocodile	crocodile
        🐢	turtle	turtle
        🦎	lizard	lizard
        🐍	snake	snake
        🐲	dragon_face	dragon,face
        🐉	dragon	dragon
        🦕	sauropod	sauropod
        🦖	t_rex	t,rex
        🐳	spouting_whale	spouting,whale
        🐋	whale	whale
        🐬	dolphin	dolphin
        🫍	orca	orca
        🦭	seal	seal
        🐟	fish	fish
        🐠	tropical_fish	tropical,fish
        🐡	blowfish	blowfish
        🦈	shark	shark
        🐙	octopus	octopus
        🐚	spiral_shell	spiral,shell
        🪸	coral	coral
        🪼	jellyfish	jellyfish
        🦀	crab	crab
        🦞	lobster	lobster
        🦐	shrimp	shrimp
        🦑	squid	squid
        🦪	oyster	oyster
        🐌	snail	snail
        🦋	butterfly	butterfly
        🐛	bug	bug
        🐜	ant	ant
        🐝	honeybee	honeybee
        🪲	beetle	beetle
        🐞	lady_beetle	lady,beetle
        🦗	cricket	cricket
        🪳	cockroach	cockroach
        🕷️	spider	spider
        🕸️	spider_web	spider,web
        🦂	scorpion	scorpion
        🦟	mosquito	mosquito
        🪰	fly	fly
        🪱	worm	worm
        🦠	microbe	microbe
        💐	bouquet	bouquet
        🌸	cherry_blossom	cherry,blossom
        💮	white_flower	white,flower
        🪷	lotus	lotus
        🏵️	rosette	rosette
        🌹	rose	rose
        🥀	wilted_flower	wilted,flower
        🌺	hibiscus	hibiscus
        🌻	sunflower	sunflower
        🌼	blossom	blossom
        🌷	tulip	tulip
        🪻	hyacinth	hyacinth
        🌱	seedling	seedling
        🪴	potted_plant	potted,plant
        🌲	evergreen_tree	evergreen,tree
        🌳	deciduous_tree	deciduous,tree
        🌴	palm_tree	palm,tree
        🌵	cactus	cactus
        🌾	sheaf_of_rice	sheaf,of,rice
        🌿	herb	herb
        ☘️	shamrock	shamrock
        🍀	four_leaf_clover	four,leaf,clover
        🍁	maple_leaf	maple,leaf
        🍂	fallen_leaf	fallen,leaf
        🍃	leaf_fluttering_in_wind	leaf,fluttering,in,wind
        🪹	empty_nest	empty,nest
        🪺	nest_with_eggs	nest,with,eggs
        🍄	mushroom	mushroom
        🪾	leafless_tree	leafless,tree
        🍇	grapes	grapes
        🍈	melon	melon
        🍉	watermelon	watermelon
        🍊	tangerine	tangerine
        🍋	lemon	lemon
        🍋‍🟩	lime	lime
        🍌	banana	banana
        🍍	pineapple	pineapple
        🥭	mango	mango
        🍎	red_apple	red,apple
        🍏	green_apple	green,apple
        🍐	pear	pear
        🍑	peach	peach
        🍒	cherries	cherries
        🍓	strawberry	strawberry
        🫐	blueberries	blueberries
        🥝	kiwi_fruit	kiwi,fruit
        🍅	tomato	tomato
        🫒	olive	olive
        🥥	coconut	coconut
        🥑	avocado	avocado
        🍆	eggplant	eggplant
        🥔	potato	potato
        🥕	carrot	carrot
        🌽	ear_of_corn	ear,of,corn
        🌶️	hot_pepper	hot,pepper
        🫑	bell_pepper	bell,pepper
        🥒	cucumber	cucumber
        🥬	leafy_green	leafy,green
        🥦	broccoli	broccoli
        🧄	garlic	garlic
        🧅	onion	onion
        🥜	peanuts	peanuts
        🫘	beans	beans
        🌰	chestnut	chestnut
        🫚	ginger_root	ginger,root
        🫛	pea_pod	pea,pod
        🍄‍🟫	brown_mushroom	brown,mushroom
        🫜	root_vegetable	root,vegetable
        🍞	bread	bread
        🥐	croissant	croissant
        🥖	baguette_bread	baguette,bread
        🫓	flatbread	flatbread
        🥨	pretzel	pretzel
        🥯	bagel	bagel
        🥞	pancakes	pancakes
        🧇	waffle	waffle
        🧀	cheese_wedge	cheese,wedge
        🍖	meat_on_bone	meat,on,bone
        🍗	poultry_leg	poultry,leg
        🥩	cut_of_meat	cut,of,meat
        🥓	bacon	bacon
        🍔	hamburger	hamburger
        🍟	french_fries	french,fries
        🍕	pizza	pizza
        🌭	hot_dog	hot,dog
        🥪	sandwich	sandwich
        🌮	taco	taco
        🌯	burrito	burrito
        🫔	tamale	tamale
        🥙	stuffed_flatbread	stuffed,flatbread
        🧆	falafel	falafel
        🥚	egg	egg
        🍳	cooking	cooking
        🥘	shallow_pan_of_food	shallow,pan,of,food
        🍲	pot_of_food	pot,of,food
        🫕	fondue	fondue
        🥣	bowl_with_spoon	bowl,with,spoon
        🥗	green_salad	green,salad
        🍿	popcorn	popcorn
        🧈	butter	butter
        🧂	salt	salt
        🥫	canned_food	canned,food
        🍱	bento_box	bento,box
        🍘	rice_cracker	rice,cracker
        🍙	rice_ball	rice,ball
        🍚	cooked_rice	cooked,rice
        🍛	curry_rice	curry,rice
        🍜	steaming_bowl	steaming,bowl
        🍝	spaghetti	spaghetti
        🍠	roasted_sweet_potato	roasted,sweet,potato
        🍢	oden	oden
        🍣	sushi	sushi
        🍤	fried_shrimp	fried,shrimp
        🍥	fish_cake_with_swirl	fish,cake,with,swirl
        🥮	moon_cake	moon,cake
        🍡	dango	dango
        🥟	dumpling	dumpling
        🥠	fortune_cookie	fortune,cookie
        🥡	takeout_box	takeout,box
        🍦	soft_ice_cream	soft,ice,cream
        🍧	shaved_ice	shaved,ice
        🍨	ice_cream	ice,cream
        🍩	doughnut	doughnut
        🍪	cookie	cookie
        🎂	birthday_cake	birthday,cake
        🍰	shortcake	shortcake
        🧁	cupcake	cupcake
        🥧	pie	pie
        🍫	chocolate_bar	chocolate,bar
        🍬	candy	candy
        🍭	lollipop	lollipop
        🍮	custard	custard
        🍯	honey_pot	honey,pot
        🍼	baby_bottle	baby,bottle
        🥛	glass_of_milk	glass,of,milk
        ☕	hot_beverage	hot,beverage
        🫖	teapot	teapot
        🍵	teacup_without_handle	teacup,without,handle
        🍶	sake	sake
        🍾	bottle_with_popping_cork	bottle,with,popping,cork
        🍷	wine_glass	wine,glass
        🍸	cocktail_glass	cocktail,glass
        🍹	tropical_drink	tropical,drink
        🍺	beer_mug	beer,mug
        🍻	clinking_beer_mugs	clinking,beer,mugs
        🥂	clinking_glasses	clinking,glasses
        🥃	tumbler_glass	tumbler,glass
        🫗	pouring_liquid	pouring,liquid
        🥤	cup_with_straw	cup,with,straw
        🧋	bubble_tea	bubble,tea
        🧃	beverage_box	beverage,box
        🧉	mate	mate
        🧊	ice	ice
        🥢	chopsticks	chopsticks
        🍽️	fork_and_knife_with_plate	fork,and,knife,with,plate
        🍴	fork_and_knife	fork,and,knife
        🥄	spoon	spoon
        🔪	kitchen_knife	kitchen,knife
        🫙	jar	jar
        🏺	amphora	amphora
        🌍	globe_showing_europe_africa	globe,showing,europe,africa
        🌎	globe_showing_americas	globe,showing,americas
        🌏	globe_showing_asia_australia	globe,showing,asia,australia
        🌐	globe_with_meridians	globe,with,meridians
        🗺️	world_map	world,map
        🗾	map_of_japan	map,of,japan
        🧭	compass	compass
        🏔️	snow_capped_mountain	snow,capped,mountain
        ⛰️	mountain	mountain
        🛘	landslide	landslide
        🌋	volcano	volcano
        🗻	mount_fuji	mount,fuji
        🏕️	camping	camping
        🏖️	beach_with_umbrella	beach,with,umbrella
        🏜️	desert	desert
        🏝️	desert_island	desert,island
        🏞️	national_park	national,park
        🏟️	stadium	stadium
        🏛️	classical_building	classical,building
        🏗️	building_construction	building,construction
        🧱	brick	brick
        🪨	rock	rock
        🪵	wood	wood
        🛖	hut	hut
        🏘️	houses	houses
        🏚️	derelict_house	derelict,house
        🏠	house	house
        🏡	house_with_garden	house,with,garden
        🏢	office_building	office,building
        🏣	japanese_post_office	japanese,post,office
        🏤	post_office	post,office
        🏥	hospital	hospital
        🏦	bank	bank
        🏨	hotel	hotel
        🏩	love_hotel	love,hotel
        🏪	convenience_store	convenience,store
        🏫	school	school
        🏬	department_store	department,store
        🏭	factory	factory
        🏯	japanese_castle	japanese,castle
        🏰	castle	castle
        💒	wedding	wedding
        🗼	tokyo_tower	tokyo,tower
        🗽	statue_of_liberty	statue,of,liberty
        ⛪	church	church
        🕌	mosque	mosque
        🛕	hindu_temple	hindu,temple
        🕍	synagogue	synagogue
        ⛩️	shinto_shrine	shinto,shrine
        🕋	kaaba	kaaba
        ⛲	fountain	fountain
        ⛺	tent	tent
        🌁	foggy	foggy
        🌃	night_with_stars	night,with,stars
        🏙️	cityscape	cityscape
        🌄	sunrise_over_mountains	sunrise,over,mountains
        🌅	sunrise	sunrise
        🌆	cityscape_at_dusk	cityscape,at,dusk
        🌇	sunset	sunset
        🌉	bridge_at_night	bridge,at,night
        ♨️	hot_springs	hot,springs
        🎠	carousel_horse	carousel,horse
        🛝	playground_slide	playground,slide
        🎡	ferris_wheel	ferris,wheel
        🎢	roller_coaster	roller,coaster
        💈	barber_pole	barber,pole
        🎪	circus_tent	circus,tent
        🚂	locomotive	locomotive
        🚃	railway_car	railway,car
        🚄	high_speed_train	high,speed,train
        🚅	bullet_train	bullet,train
        🚆	train	train
        🚇	metro	metro
        🚈	light_rail	light,rail
        🚉	station	station
        🚊	tram	tram
        🚝	monorail	monorail
        🚞	mountain_railway	mountain,railway
        🚋	tram_car	tram,car
        🚌	bus	bus
        🚍	oncoming_bus	oncoming,bus
        🚎	trolleybus	trolleybus
        🚐	minibus	minibus
        🚑	ambulance	ambulance
        🚒	fire_engine	fire,engine
        🚓	police_car	police,car
        🚔	oncoming_police_car	oncoming,police,car
        🚕	taxi	taxi
        🚖	oncoming_taxi	oncoming,taxi
        🚗	automobile	automobile
        🚘	oncoming_automobile	oncoming,automobile
        🚙	sport_utility_vehicle	sport,utility,vehicle
        🛻	pickup_truck	pickup,truck
        🚚	delivery_truck	delivery,truck
        🚛	articulated_lorry	articulated,lorry
        🚜	tractor	tractor
        🏎️	racing_car	racing,car
        🏍️	motorcycle	motorcycle
        🛵	motor_scooter	motor,scooter
        🦽	manual_wheelchair	manual,wheelchair
        🦼	motorized_wheelchair	motorized,wheelchair
        🛺	auto_rickshaw	auto,rickshaw
        🚲	bicycle	bicycle
        🛴	kick_scooter	kick,scooter
        🛹	skateboard	skateboard
        🛼	roller_skate	roller,skate
        🚏	bus_stop	bus,stop
        🛣️	motorway	motorway
        🛤️	railway_track	railway,track
        🛢️	oil_drum	oil,drum
        ⛽	fuel_pump	fuel,pump
        🛞	wheel	wheel
        🚨	police_car_light	police,car,light
        🚥	horizontal_traffic_light	horizontal,traffic,light
        🚦	vertical_traffic_light	vertical,traffic,light
        🛑	stop_sign	stop,sign
        🚧	construction	construction
        ⚓	anchor	anchor
        🛟	ring_buoy	ring,buoy
        ⛵	sailboat	sailboat
        🛶	canoe	canoe
        🚤	speedboat	speedboat
        🛳️	passenger_ship	passenger,ship
        ⛴️	ferry	ferry
        🛥️	motor_boat	motor,boat
        🚢	ship	ship
        ✈️	airplane	airplane
        🛩️	small_airplane	small,airplane
        🛫	airplane_departure	airplane,departure
        🛬	airplane_arrival	airplane,arrival
        🪂	parachute	parachute
        💺	seat	seat
        🚁	helicopter	helicopter
        🚟	suspension_railway	suspension,railway
        🚠	mountain_cableway	mountain,cableway
        🚡	aerial_tramway	aerial,tramway
        🛰️	satellite	satellite
        🚀	rocket	rocket
        🛸	flying_saucer	flying,saucer
        🛎️	bellhop_bell	bellhop,bell
        🧳	luggage	luggage
        ⌛	hourglass_done	hourglass,done
        ⏳	hourglass_not_done	hourglass,not,done
        ⌚	watch	watch
        ⏰	alarm_clock	alarm,clock
        ⏱️	stopwatch	stopwatch
        ⏲️	timer_clock	timer,clock
        🕰️	mantelpiece_clock	mantelpiece,clock
        🕛	twelve_o_clock	twelve,o,clock
        🕧	twelve_thirty	twelve,thirty
        🕐	one_o_clock	one,o,clock
        🕜	one_thirty	one,thirty
        🕑	two_o_clock	two,o,clock
        🕝	two_thirty	two,thirty
        🕒	three_o_clock	three,o,clock
        🕞	three_thirty	three,thirty
        🕓	four_o_clock	four,o,clock
        🕟	four_thirty	four,thirty
        🕔	five_o_clock	five,o,clock
        🕠	five_thirty	five,thirty
        🕕	six_o_clock	six,o,clock
        🕡	six_thirty	six,thirty
        🕖	seven_o_clock	seven,o,clock
        🕢	seven_thirty	seven,thirty
        🕗	eight_o_clock	eight,o,clock
        🕣	eight_thirty	eight,thirty
        🕘	nine_o_clock	nine,o,clock
        🕤	nine_thirty	nine,thirty
        🕙	ten_o_clock	ten,o,clock
        🕥	ten_thirty	ten,thirty
        🕚	eleven_o_clock	eleven,o,clock
        🕦	eleven_thirty	eleven,thirty
        🌑	new_moon	new,moon
        🌒	waxing_crescent_moon	waxing,crescent,moon
        🌓	first_quarter_moon	first,quarter,moon
        🌔	waxing_gibbous_moon	waxing,gibbous,moon
        🌕	full_moon	full,moon
        🌖	waning_gibbous_moon	waning,gibbous,moon
        🌗	last_quarter_moon	last,quarter,moon
        🌘	waning_crescent_moon	waning,crescent,moon
        🌙	crescent_moon	crescent,moon
        🌚	new_moon_face	new,moon,face
        🌛	first_quarter_moon_face	first,quarter,moon,face
        🌜	last_quarter_moon_face	last,quarter,moon,face
        🌡️	thermometer	thermometer
        ☀️	sun	sun
        🌝	full_moon_face	full,moon,face
        🌞	sun_with_face	sun,with,face
        🪐	ringed_planet	ringed,planet
        ⭐	star	star
        🌟	glowing_star	glowing,star
        🌠	shooting_star	shooting,star
        🌌	milky_way	milky,way
        ☁️	cloud	cloud
        ⛅	sun_behind_cloud	sun,behind,cloud
        ⛈️	cloud_with_lightning_and_rain	cloud,with,lightning,and,rain
        🌤️	sun_behind_small_cloud	sun,behind,small,cloud
        🌥️	sun_behind_large_cloud	sun,behind,large,cloud
        🌦️	sun_behind_rain_cloud	sun,behind,rain,cloud
        🌧️	cloud_with_rain	cloud,with,rain
        🌨️	cloud_with_snow	cloud,with,snow
        🌩️	cloud_with_lightning	cloud,with,lightning
        🌪️	tornado	tornado
        🌫️	fog	fog
        🌬️	wind_face	wind,face
        🌀	cyclone	cyclone
        🌈	rainbow	rainbow
        🌂	closed_umbrella	closed,umbrella
        ☂️	umbrella	umbrella
        ☔	umbrella_with_rain_drops	umbrella,with,rain,drops
        ⛱️	umbrella_on_ground	umbrella,on,ground
        ⚡	high_voltage	high,voltage
        ❄️	snowflake	snowflake
        ☃️	snowman	snowman
        ⛄	snowman_without_snow	snowman,without,snow
        ☄️	comet	comet
        🔥	fire	fire
        💧	droplet	droplet
        🌊	water_wave	water,wave
        🎃	jack_o_lantern	jack,o,lantern
        🎄	christmas_tree	christmas,tree
        🎆	fireworks	fireworks
        🎇	sparkler	sparkler
        🧨	firecracker	firecracker
        ✨	sparkles	sparkles
        🎈	balloon	balloon
        🎉	party_popper	party,popper
        🎊	confetti_ball	confetti,ball
        🎋	tanabata_tree	tanabata,tree
        🎍	pine_decoration	pine,decoration
        🎎	japanese_dolls	japanese,dolls
        🎏	carp_streamer	carp,streamer
        🎐	wind_chime	wind,chime
        🎑	moon_viewing_ceremony	moon,viewing,ceremony
        🧧	red_envelope	red,envelope
        🎀	ribbon	ribbon
        🎁	wrapped_gift	wrapped,gift
        🎗️	reminder_ribbon	reminder,ribbon
        🎟️	admission_tickets	admission,tickets
        🎫	ticket	ticket
        🎖️	military_medal	military,medal
        🏆	trophy	trophy
        🏅	sports_medal	sports,medal
        🥇	1st_place_medal	1st,place,medal
        🥈	2nd_place_medal	2nd,place,medal
        🥉	3rd_place_medal	3rd,place,medal
        ⚽	soccer_ball	soccer,ball
        ⚾	baseball	baseball
        🥎	softball	softball
        🏀	basketball	basketball
        🏐	volleyball	volleyball
        🏈	american_football	american,football
        🏉	rugby_football	rugby,football
        🎾	tennis	tennis
        🥏	flying_disc	flying,disc
        🎳	bowling	bowling
        🏏	cricket_game	cricket,game
        🏑	field_hockey	field,hockey
        🏒	ice_hockey	ice,hockey
        🥍	lacrosse	lacrosse
        🏓	ping_pong	ping,pong
        🏸	badminton	badminton
        🥊	boxing_glove	boxing,glove
        🥋	martial_arts_uniform	martial,arts,uniform
        🥅	goal_net	goal,net
        ⛳	flag_in_hole	flag,in,hole
        ⛸️	ice_skate	ice,skate
        🎣	fishing_pole	fishing,pole
        🤿	diving_mask	diving,mask
        🎽	running_shirt	running,shirt
        🎿	skis	skis
        🛷	sled	sled
        🥌	curling_stone	curling,stone
        🎯	bullseye	bullseye
        🪀	yo_yo	yo
        🪁	kite	kite
        🔫	water_pistol	water,pistol
        🎱	pool_8_ball	pool,8,ball
        🔮	crystal_ball	crystal,ball
        🪄	magic_wand	magic,wand
        🎮	video_game	video,game
        🕹️	joystick	joystick
        🎰	slot_machine	slot,machine
        🎲	game_die	game,die
        🧩	puzzle_piece	puzzle,piece
        🧸	teddy_bear	teddy,bear
        🪅	pi_ata	pi,ata
        🪩	mirror_ball	mirror,ball
        🪆	nesting_dolls	nesting,dolls
        ♠️	spade_suit	spade,suit
        ♥️	heart_suit	heart,suit
        ♦️	diamond_suit	diamond,suit
        ♣️	club_suit	club,suit
        ♟️	chess_pawn	chess,pawn
        🃏	joker	joker
        🀄	mahjong_red_dragon	mahjong,red,dragon
        🎴	flower_playing_cards	flower,playing,cards
        🎭	performing_arts	performing,arts
        🖼️	framed_picture	framed,picture
        🎨	artist_palette	artist,palette
        🧵	thread	thread
        🪡	sewing_needle	sewing,needle
        🧶	yarn	yarn
        🪢	knot	knot
        👓	glasses	glasses
        🕶️	sunglasses	sunglasses
        🥽	goggles	goggles
        🥼	lab_coat	lab,coat
        🦺	safety_vest	safety,vest
        👔	necktie	necktie
        👕	t_shirt	t,shirt
        👖	jeans	jeans
        🧣	scarf	scarf
        🧤	gloves	gloves
        🧥	coat	coat
        🧦	socks	socks
        👗	dress	dress
        👘	kimono	kimono
        🥻	sari	sari
        🩱	one_piece_swimsuit	one,piece,swimsuit
        🩲	briefs	briefs
        🩳	shorts	shorts
        👙	bikini	bikini
        👚	woman_s_clothes	woman,s,clothes
        🪭	folding_hand_fan	folding,hand,fan
        👛	purse	purse
        👜	handbag	handbag
        👝	clutch_bag	clutch,bag
        🛍️	shopping_bags	shopping,bags
        🎒	backpack	backpack
        🩴	thong_sandal	thong,sandal
        👞	man_s_shoe	man,s,shoe
        👟	running_shoe	running,shoe
        🥾	hiking_boot	hiking,boot
        🥿	flat_shoe	flat,shoe
        👠	high_heeled_shoe	high,heeled,shoe
        👡	woman_s_sandal	woman,s,sandal
        🩰	ballet_shoes	ballet,shoes
        👢	woman_s_boot	woman,s,boot
        🪮	hair_pick	hair,pick
        👑	crown	crown
        👒	woman_s_hat	woman,s,hat
        🎩	top_hat	top,hat
        🎓	graduation_cap	graduation,cap
        🧢	billed_cap	billed,cap
        🪖	military_helmet	military,helmet
        ⛑️	rescue_worker_s_helmet	rescue,worker,s,helmet
        📿	prayer_beads	prayer,beads
        💄	lipstick	lipstick
        💍	ring	ring
        💎	gem_stone	gem,stone
        🔇	muted_speaker	muted,speaker
        🔈	speaker_low_volume	speaker,low,volume
        🔉	speaker_medium_volume	speaker,medium,volume
        🔊	speaker_high_volume	speaker,high,volume
        📢	loudspeaker	loudspeaker
        📣	megaphone	megaphone
        📯	postal_horn	postal,horn
        🔔	bell	bell
        🔕	bell_with_slash	bell,with,slash
        🎼	musical_score	musical,score
        🎵	musical_note	musical,note
        🎶	musical_notes	musical,notes
        🎙️	studio_microphone	studio,microphone
        🎚️	level_slider	level,slider
        🎛️	control_knobs	control,knobs
        🎤	microphone	microphone
        🎧	headphone	headphone
        📻	radio	radio
        🎷	saxophone	saxophone
        🎺	trumpet	trumpet
        🪊	trombone	trombone
        🪗	accordion	accordion
        🎸	guitar	guitar
        🎹	musical_keyboard	musical,keyboard
        🎻	violin	violin
        🪕	banjo	banjo
        🥁	drum	drum
        🪘	long_drum	long,drum
        🪇	maracas	maracas
        🪈	flute	flute
        🪉	harp	harp
        📱	mobile_phone	mobile,phone
        📲	mobile_phone_with_arrow	mobile,phone,with,arrow
        ☎️	telephone	telephone
        📞	telephone_receiver	telephone,receiver
        📟	pager	pager
        📠	fax_machine	fax,machine
        🔋	battery	battery
        🪫	low_battery	low,battery
        🔌	electric_plug	electric,plug
        💻	laptop	laptop
        🖥️	desktop_computer	desktop,computer
        🖨️	printer	printer
        ⌨️	keyboard	keyboard
        🖱️	computer_mouse	computer,mouse
        🖲️	trackball	trackball
        💽	computer_disk	computer,disk
        💾	floppy_disk	floppy,disk
        💿	optical_disk	optical,disk
        📀	dvd	dvd
        🧮	abacus	abacus
        🎥	movie_camera	movie,camera
        🎞️	film_frames	film,frames
        📽️	film_projector	film,projector
        🎬	clapper_board	clapper,board
        📺	television	television
        📷	camera	camera
        📸	camera_with_flash	camera,with,flash
        📹	video_camera	video,camera
        📼	videocassette	videocassette
        🔍	magnifying_glass_tilted_left	magnifying,glass,tilted,left
        🔎	magnifying_glass_tilted_right	magnifying,glass,tilted,right
        🕯️	candle	candle
        💡	light_bulb	light,bulb
        🔦	flashlight	flashlight
        🏮	red_paper_lantern	red,paper,lantern
        🪔	diya_lamp	diya,lamp
        📔	notebook_with_decorative_cover	notebook,with,decorative,cover
        📕	closed_book	closed,book
        📖	open_book	open,book
        📗	green_book	green,book
        📘	blue_book	blue,book
        📙	orange_book	orange,book
        📚	books	books
        📓	notebook	notebook
        📒	ledger	ledger
        📃	page_with_curl	page,with,curl
        📜	scroll	scroll
        📄	page_facing_up	page,facing,up
        📰	newspaper	newspaper
        🗞️	rolled_up_newspaper	rolled,up,newspaper
        📑	bookmark_tabs	bookmark,tabs
        🔖	bookmark	bookmark
        🏷️	label	label
        🪙	coin	coin
        💰	money_bag	money,bag
        🪎	treasure_chest	treasure,chest
        💴	yen_banknote	yen,banknote
        💵	dollar_banknote	dollar,banknote
        💶	euro_banknote	euro,banknote
        💷	pound_banknote	pound,banknote
        💸	money_with_wings	money,with,wings
        💳	credit_card	credit,card
        🧾	receipt	receipt
        💹	chart_increasing_with_yen	chart,increasing,with,yen
        ✉️	envelope	envelope
        📧	e_mail	e,mail
        📨	incoming_envelope	incoming,envelope
        📩	envelope_with_arrow	envelope,with,arrow
        📤	outbox_tray	outbox,tray
        📥	inbox_tray	inbox,tray
        📦	package	package
        📫	closed_mailbox_with_raised_flag	closed,mailbox,with,raised,flag
        📪	closed_mailbox_with_lowered_flag	closed,mailbox,with,lowered,flag
        📬	open_mailbox_with_raised_flag	open,mailbox,with,raised,flag
        📭	open_mailbox_with_lowered_flag	open,mailbox,with,lowered,flag
        📮	postbox	postbox
        🗳️	ballot_box_with_ballot	ballot,box,with
        ✏️	pencil	pencil
        ✒️	black_nib	black,nib
        🖋️	fountain_pen	fountain,pen
        🖊️	pen	pen
        🖌️	paintbrush	paintbrush
        🖍️	crayon	crayon
        📝	memo	memo
        💼	briefcase	briefcase
        📁	file_folder	file,folder
        📂	open_file_folder	open,file,folder
        🗂️	card_index_dividers	card,index,dividers
        📅	calendar	calendar
        📆	tear_off_calendar	tear,off,calendar
        🗒️	spiral_notepad	spiral,notepad
        🗓️	spiral_calendar	spiral,calendar
        📇	card_index	card,index
        📈	chart_increasing	chart,increasing
        📉	chart_decreasing	chart,decreasing
        📊	bar_chart	bar,chart
        📋	clipboard	clipboard
        📌	pushpin	pushpin
        📍	round_pushpin	round,pushpin
        📎	paperclip	paperclip
        🖇️	linked_paperclips	linked,paperclips
        📏	straight_ruler	straight,ruler
        📐	triangular_ruler	triangular,ruler
        ✂️	scissors	scissors
        🗃️	card_file_box	card,file,box
        🗄️	file_cabinet	file,cabinet
        🗑️	wastebasket	wastebasket
        🔒	locked	locked
        🔓	unlocked	unlocked
        🔏	locked_with_pen	locked,with,pen
        🔐	locked_with_key	locked,with,key
        🔑	key	key
        🗝️	old_key	old,key
        🔨	hammer	hammer
        🪓	axe	axe
        ⛏️	pick	pick
        ⚒️	hammer_and_pick	hammer,and,pick
        🛠️	hammer_and_wrench	hammer,and,wrench
        🗡️	dagger	dagger
        ⚔️	crossed_swords	crossed,swords
        💣	bomb	bomb
        🪃	boomerang	boomerang
        🏹	bow_and_arrow	bow,and,arrow
        🛡️	shield	shield
        🪚	carpentry_saw	carpentry,saw
        🔧	wrench	wrench
        🪛	screwdriver	screwdriver
        🔩	nut_and_bolt	nut,and,bolt
        ⚙️	gear	gear
        🗜️	clamp	clamp
        ⚖️	balance_scale	balance,scale
        🦯	white_cane	white,cane
        🔗	link	link
        ⛓️‍💥	broken_chain	broken,chain
        ⛓️	chains	chains
        🪝	hook	hook
        🧰	toolbox	toolbox
        🧲	magnet	magnet
        🪜	ladder	ladder
        🪏	shovel	shovel
        ⚗️	alembic	alembic
        🧪	test_tube	test,tube
        🧫	petri_dish	petri,dish
        🧬	dna	dna
        🔬	microscope	microscope
        🔭	telescope	telescope
        📡	satellite_antenna	satellite,antenna
        💉	syringe	syringe
        🩸	drop_of_blood	drop,of,blood
        💊	pill	pill
        🩹	adhesive_bandage	adhesive,bandage
        🩼	crutch	crutch
        🩺	stethoscope	stethoscope
        🩻	x_ray	x,ray
        🚪	door	door
        🛗	elevator	elevator
        🪞	mirror	mirror
        🪟	window	window
        🛏️	bed	bed
        🛋️	couch_and_lamp	couch,and,lamp
        🪑	chair	chair
        🚽	toilet	toilet
        🪠	plunger	plunger
        🚿	shower	shower
        🛁	bathtub	bathtub
        🪤	mouse_trap	mouse,trap
        🪒	razor	razor
        🧴	lotion_bottle	lotion,bottle
        🧷	safety_pin	safety,pin
        🧹	broom	broom
        🧺	basket	basket
        🧻	roll_of_paper	roll,of,paper
        🪣	bucket	bucket
        🧼	soap	soap
        🫧	bubbles	bubbles
        🪥	toothbrush	toothbrush
        🧽	sponge	sponge
        🧯	fire_extinguisher	fire,extinguisher
        🛒	shopping_cart	shopping,cart
        🚬	cigarette	cigarette
        ⚰️	coffin	coffin
        🪦	headstone	headstone
        ⚱️	funeral_urn	funeral,urn
        🧿	nazar_amulet	nazar,amulet
        🪬	hamsa	hamsa
        🗿	moai	moai
        🪧	placard	placard
        🪪	identification_card	identification,card
        🏧	atm_sign	atm,sign
        🚮	litter_in_bin_sign	litter,in,bin,sign
        🚰	potable_water	potable,water
        ♿	wheelchair_symbol	wheelchair,symbol
        🚹	men_s_room	men,s,room
        🚺	women_s_room	women,s,room
        🚻	restroom	restroom
        🚼	baby_symbol	baby,symbol
        🚾	water_closet	water,closet
        🛂	passport_control	passport,control
        🛃	customs	customs
        🛄	baggage_claim	baggage,claim
        🛅	left_luggage	left,luggage
        ⚠️	warning	warning
        🚸	children_crossing	children,crossing
        ⛔	no_entry	no,entry
        🚫	prohibited	prohibited
        🚳	no_bicycles	no,bicycles
        🚭	no_smoking	no,smoking
        🚯	no_littering	no,littering
        🚱	non_potable_water	non,potable,water
        🚷	no_pedestrians	no,pedestrians
        📵	no_mobile_phones	no,mobile,phones
        🔞	no_one_under_eighteen	no,one,under,eighteen
        ☢️	radioactive	radioactive
        ☣️	biohazard	biohazard
        ⬆️	up_arrow	up,arrow
        ↗️	up_right_arrow	up,right,arrow
        ➡️	right_arrow	right,arrow
        ↘️	down_right_arrow	down,right,arrow
        ⬇️	down_arrow	down,arrow
        ↙️	down_left_arrow	down,left,arrow
        ⬅️	left_arrow	left,arrow
        ↖️	up_left_arrow	up,left,arrow
        ↕️	up_down_arrow	up,down,arrow
        ↔️	left_right_arrow	left,right,arrow
        ↩️	right_arrow_curving_left	right,arrow,curving,left
        ↪️	left_arrow_curving_right	left,arrow,curving,right
        ⤴️	right_arrow_curving_up	right,arrow,curving,up
        ⤵️	right_arrow_curving_down	right,arrow,curving,down
        🔃	clockwise_vertical_arrows	clockwise,vertical,arrows
        🔄	counterclockwise_arrows_button	counterclockwise,arrows,button
        🔙	back_arrow	back,arrow
        🔚	end_arrow	end,arrow
        🔛	on_arrow	on,arrow
        🔜	soon_arrow	soon,arrow
        🔝	top_arrow	top,arrow
        🛐	place_of_worship	place,of,worship
        ⚛️	atom_symbol	atom,symbol
        🕉️	om	om
        ✡️	star_of_david	star,of,david
        ☸️	wheel_of_dharma	wheel,of,dharma
        ☯️	yin_yang	yin,yang
        ✝️	latin_cross	latin,cross
        ☦️	orthodox_cross	orthodox,cross
        ☪️	star_and_crescent	star,and,crescent
        ☮️	peace_symbol	peace,symbol
        🕎	menorah	menorah
        🔯	dotted_six_pointed_star	dotted,six,pointed,star
        🪯	khanda	khanda
        ♈	aries	aries
        ♉	taurus	taurus
        ♊	gemini	gemini
        ♋	cancer	cancer
        ♌	leo	leo
        ♍	virgo	virgo
        ♎	libra	libra
        ♏	scorpio	scorpio
        ♐	sagittarius	sagittarius
        ♑	capricorn	capricorn
        ♒	aquarius	aquarius
        ♓	pisces	pisces
        ⛎	ophiuchus	ophiuchus
        🔀	shuffle_tracks_button	shuffle,tracks,button
        🔁	repeat_button	repeat,button
        🔂	repeat_single_button	repeat,single,button
        ▶️	play_button	play,button
        ⏩	fast_forward_button	fast,forward,button
        ⏭️	next_track_button	next,track,button
        ⏯️	play_or_pause_button	play,or,pause,button
        ◀️	reverse_button	reverse,button
        ⏪	fast_reverse_button	fast,reverse,button
        ⏮️	last_track_button	last,track,button
        🔼	upwards_button	upwards,button
        ⏫	fast_up_button	fast,up,button
        🔽	downwards_button	downwards,button
        ⏬	fast_down_button	fast,down,button
        ⏸️	pause_button	pause,button
        ⏹️	stop_button	stop,button
        ⏺️	record_button	record,button
        ⏏️	eject_button	eject,button
        🎦	cinema	cinema
        🔅	dim_button	dim,button
        🔆	bright_button	bright,button
        📶	antenna_bars	antenna,bars
        🛜	wireless	wireless
        📳	vibration_mode	vibration,mode
        📴	mobile_phone_off	mobile,phone,off
        ♀️	female_sign	female,sign
        ♂️	male_sign	male,sign
        ⚧️	transgender_symbol	transgender,symbol
        ✖️	multiply	multiply
        ➕	plus	plus
        ➖	minus	minus
        ➗	divide	divide
        🟰	heavy_equals_sign	heavy,equals,sign
        ♾️	infinity	infinity
        ‼️	double_exclamation_mark	double,exclamation,mark
        ⁉️	exclamation_question_mark	exclamation,question,mark
        ❓	red_question_mark	red,question,mark
        ❔	white_question_mark	white,question,mark
        ❕	white_exclamation_mark	white,exclamation,mark
        ❗	red_exclamation_mark	red,exclamation,mark
        〰️	wavy_dash	wavy,dash
        💱	currency_exchange	currency,exchange
        💲	heavy_dollar_sign	heavy,dollar,sign
        ⚕️	medical_symbol	medical,symbol
        ♻️	recycling_symbol	recycling,symbol
        ⚜️	fleur_de_lis	fleur,de,lis
        🔱	trident_emblem	trident,emblem
        📛	name_badge	name,badge
        🔰	japanese_symbol_for_beginner	japanese,symbol,for,beginner
        ⭕	hollow_red_circle	hollow,red,circle
        ✅	check_mark_button	check,mark,button
        ☑️	check_box_with_check	check,box,with
        ✔️	check_mark	check,mark
        ❌	cross_mark	cross,mark
        ❎	cross_mark_button	cross,mark,button
        ➰	curly_loop	curly,loop
        ➿	double_curly_loop	double,curly,loop
        〽️	part_alternation_mark	part,alternation,mark
        ✳️	eight_spoked_asterisk	eight,spoked,asterisk
        ✴️	eight_pointed_star	eight,pointed,star
        ❇️	sparkle	sparkle
        ©️	copyright	copyright
        ®️	registered	registered
        ™️	trade_mark	trade,mark
        🫟	splatter	splatter
        #️⃣	keycap_hash	keycap,hash
        *️⃣	keycap_asterisk	keycap,asterisk
        0️⃣	keycap_0	keycap,0
        1️⃣	keycap_1	keycap,1
        2️⃣	keycap_2	keycap,2
        3️⃣	keycap_3	keycap,3
        4️⃣	keycap_4	keycap,4
        5️⃣	keycap_5	keycap,5
        6️⃣	keycap_6	keycap,6
        7️⃣	keycap_7	keycap,7
        8️⃣	keycap_8	keycap,8
        9️⃣	keycap_9	keycap,9
        🔟	keycap_10	keycap,10
        🔠	input_latin_uppercase	input,latin,uppercase
        🔡	input_latin_lowercase	input,latin,lowercase
        🔢	input_numbers	input,numbers
        🔣	input_symbols	input,symbols
        🔤	input_latin_letters	input,latin,letters
        🅰️	a_button_blood_type	a,button,blood,type
        🆎	ab_button_blood_type	ab,button,blood,type
        🅱️	b_button_blood_type	b,button,blood,type
        🆑	cl_button	cl,button
        🆒	cool_button	cool,button
        🆓	free_button	free,button
        ℹ️	information	information
        🆔	id_button	id,button
        Ⓜ️	circled_m	circled,m
        🆕	new_button	new,button
        🆖	ng_button	ng,button
        🅾️	o_button_blood_type	o,button,blood,type
        🆗	ok_button	ok,button
        🅿️	p_button	p,button
        🆘	sos_button	sos,button
        🆙	up_button	up,button
        🆚	vs_button	vs,button
        🈁	japanese_here_button	japanese,here,button
        🈂️	japanese_service_charge_button	japanese,service,charge,button
        🈷️	japanese_monthly_amount_button	japanese,monthly,amount,button
        🈶	japanese_not_free_of_charge_button	japanese,not,free,of,charge,button
        🈯	japanese_reserved_button	japanese,reserved,button
        🉐	japanese_bargain_button	japanese,bargain,button
        🈹	japanese_discount_button	japanese,discount,button
        🈚	japanese_free_of_charge_button	japanese,free,of,charge,button
        🈲	japanese_prohibited_button	japanese,prohibited,button
        🉑	japanese_acceptable_button	japanese,acceptable,button
        🈸	japanese_application_button	japanese,application,button
        🈴	japanese_passing_grade_button	japanese,passing,grade,button
        🈳	japanese_vacancy_button	japanese,vacancy,button
        ㊗️	japanese_congratulations_button	japanese,congratulations,button
        ㊙️	japanese_secret_button	japanese,secret,button
        🈺	japanese_open_for_business_button	japanese,open,for,business,button
        🈵	japanese_no_vacancy_button	japanese,no,vacancy,button
        🔴	red_circle	red,circle
        🟠	orange_circle	orange,circle
        🟡	yellow_circle	yellow,circle
        🟢	green_circle	green,circle
        🔵	blue_circle	blue,circle
        🟣	purple_circle	purple,circle
        🟤	brown_circle	brown,circle
        ⚫	black_circle	black,circle
        ⚪	white_circle	white,circle
        🟥	red_square	red,square
        🟧	orange_square	orange,square
        🟨	yellow_square	yellow,square
        🟩	green_square	green,square
        🟦	blue_square	blue,square
        🟪	purple_square	purple,square
        🟫	brown_square	brown,square
        ⬛	black_large_square	black,large,square
        ⬜	white_large_square	white,large,square
        ◼️	black_medium_square	black,medium,square
        ◻️	white_medium_square	white,medium,square
        ◾	black_medium_small_square	black,medium,small,square
        ◽	white_medium_small_square	white,medium,small,square
        ▪️	black_small_square	black,small,square
        ▫️	white_small_square	white,small,square
        🔶	large_orange_diamond	large,orange,diamond
        🔷	large_blue_diamond	large,blue,diamond
        🔸	small_orange_diamond	small,orange,diamond
        🔹	small_blue_diamond	small,blue,diamond
        🔺	red_triangle_pointed_up	red,triangle,pointed,up
        🔻	red_triangle_pointed_down	red,triangle,pointed,down
        💠	diamond_with_a_dot	diamond,with,a,dot
        🔘	radio_button	radio,button
        🔳	white_square_button	white,square,button
        🔲	black_square_button	black,square,button
        🏁	chequered_flag	chequered,flag
        🚩	triangular_flag	triangular,flag
        🎌	crossed_flags	crossed,flags
        🏴	black_flag	black,flag
        🏳️	white_flag	white,flag
        🏳️‍🌈	rainbow_flag	rainbow,flag
        🏳️‍⚧️	transgender_flag	transgender,flag
        🏴‍☠️	pirate_flag	pirate,flag
        🇦🇨	flag_ascension_island	flag,ascension,island
        🇦🇩	flag_andorra	flag,andorra
        🇦🇪	flag_united_arab_emirates	flag,united,arab,emirates
        🇦🇫	flag_afghanistan	flag,afghanistan
        🇦🇬	flag_antigua_and_barbuda	flag,antigua,and,barbuda
        🇦🇮	flag_anguilla	flag,anguilla
        🇦🇱	flag_albania	flag,albania
        🇦🇲	flag_armenia	flag,armenia
        🇦🇴	flag_angola	flag,angola
        🇦🇶	flag_antarctica	flag,antarctica
        🇦🇷	flag_argentina	flag,argentina
        🇦🇸	flag_american_samoa	flag,american,samoa
        🇦🇹	flag_austria	flag,austria
        🇦🇺	flag_australia	flag,australia
        🇦🇼	flag_aruba	flag,aruba
        🇦🇽	flag_land_islands	flag,land,islands
        🇦🇿	flag_azerbaijan	flag,azerbaijan
        🇧🇦	flag_bosnia_and_herzegovina	flag,bosnia,and,herzegovina
        🇧🇧	flag_barbados	flag,barbados
        🇧🇩	flag_bangladesh	flag,bangladesh
        🇧🇪	flag_belgium	flag,belgium
        🇧🇫	flag_burkina_faso	flag,burkina,faso
        🇧🇬	flag_bulgaria	flag,bulgaria
        🇧🇭	flag_bahrain	flag,bahrain
        🇧🇮	flag_burundi	flag,burundi
        🇧🇯	flag_benin	flag,benin
        🇧🇱	flag_st_barth_lemy	flag,st,barth,lemy
        🇧🇲	flag_bermuda	flag,bermuda
        🇧🇳	flag_brunei	flag,brunei
        🇧🇴	flag_bolivia	flag,bolivia
        🇧🇶	flag_caribbean_netherlands	flag,caribbean,netherlands
        🇧🇷	flag_brazil	flag,brazil
        🇧🇸	flag_bahamas	flag,bahamas
        🇧🇹	flag_bhutan	flag,bhutan
        🇧🇻	flag_bouvet_island	flag,bouvet,island
        🇧🇼	flag_botswana	flag,botswana
        🇧🇾	flag_belarus	flag,belarus
        🇧🇿	flag_belize	flag,belize
        🇨🇦	flag_canada	flag,canada
        🇨🇨	flag_cocos_keeling_islands	flag,cocos,keeling,islands
        🇨🇩	flag_congo_kinshasa	flag,congo,kinshasa
        🇨🇫	flag_central_african_republic	flag,central,african,republic
        🇨🇬	flag_congo_brazzaville	flag,congo,brazzaville
        🇨🇭	flag_switzerland	flag,switzerland
        🇨🇮	flag_c_te_d_ivoire	flag,c,te,d,ivoire
        🇨🇰	flag_cook_islands	flag,cook,islands
        🇨🇱	flag_chile	flag,chile
        🇨🇲	flag_cameroon	flag,cameroon
        🇨🇳	flag_china	flag,china
        🇨🇴	flag_colombia	flag,colombia
        🇨🇵	flag_clipperton_island	flag,clipperton,island
        🇨🇶	flag_sark	flag,sark
        🇨🇷	flag_costa_rica	flag,costa,rica
        🇨🇺	flag_cuba	flag,cuba
        🇨🇻	flag_cape_verde	flag,cape,verde
        🇨🇼	flag_cura_ao	flag,cura,ao
        🇨🇽	flag_christmas_island	flag,christmas,island
        🇨🇾	flag_cyprus	flag,cyprus
        🇨🇿	flag_czechia	flag,czechia
        🇩🇪	flag_germany	flag,germany
        🇩🇬	flag_diego_garcia	flag,diego,garcia
        🇩🇯	flag_djibouti	flag,djibouti
        🇩🇰	flag_denmark	flag,denmark
        🇩🇲	flag_dominica	flag,dominica
        🇩🇴	flag_dominican_republic	flag,dominican,republic
        🇩🇿	flag_algeria	flag,algeria
        🇪🇦	flag_ceuta_and_melilla	flag,ceuta,and,melilla
        🇪🇨	flag_ecuador	flag,ecuador
        🇪🇪	flag_estonia	flag,estonia
        🇪🇬	flag_egypt	flag,egypt
        🇪🇭	flag_western_sahara	flag,western,sahara
        🇪🇷	flag_eritrea	flag,eritrea
        🇪🇸	flag_spain	flag,spain
        🇪🇹	flag_ethiopia	flag,ethiopia
        🇪🇺	flag_european_union	flag,european,union
        🇫🇮	flag_finland	flag,finland
        🇫🇯	flag_fiji	flag,fiji
        🇫🇰	flag_falkland_islands	flag,falkland,islands
        🇫🇲	flag_micronesia	flag,micronesia
        🇫🇴	flag_faroe_islands	flag,faroe,islands
        🇫🇷	flag_france	flag,france
        🇬🇦	flag_gabon	flag,gabon
        🇬🇧	flag_united_kingdom	flag,united,kingdom
        🇬🇩	flag_grenada	flag,grenada
        🇬🇪	flag_georgia	flag,georgia
        🇬🇫	flag_french_guiana	flag,french,guiana
        🇬🇬	flag_guernsey	flag,guernsey
        🇬🇭	flag_ghana	flag,ghana
        🇬🇮	flag_gibraltar	flag,gibraltar
        🇬🇱	flag_greenland	flag,greenland
        🇬🇲	flag_gambia	flag,gambia
        🇬🇳	flag_guinea	flag,guinea
        🇬🇵	flag_guadeloupe	flag,guadeloupe
        🇬🇶	flag_equatorial_guinea	flag,equatorial,guinea
        🇬🇷	flag_greece	flag,greece
        🇬🇸	flag_south_georgia_and_south_sandwich_islands	flag,south,georgia,and,sandwich,islands
        🇬🇹	flag_guatemala	flag,guatemala
        🇬🇺	flag_guam	flag,guam
        🇬🇼	flag_guinea_bissau	flag,guinea,bissau
        🇬🇾	flag_guyana	flag,guyana
        🇭🇰	flag_hong_kong_sar_china	flag,hong,kong,sar,china
        🇭🇲	flag_heard_and_mcdonald_islands	flag,heard,and,mcdonald,islands
        🇭🇳	flag_honduras	flag,honduras
        🇭🇷	flag_croatia	flag,croatia
        🇭🇹	flag_haiti	flag,haiti
        🇭🇺	flag_hungary	flag,hungary
        🇮🇨	flag_canary_islands	flag,canary,islands
        🇮🇩	flag_indonesia	flag,indonesia
        🇮🇪	flag_ireland	flag,ireland
        🇮🇱	flag_israel	flag,israel
        🇮🇲	flag_isle_of_man	flag,isle,of,man
        🇮🇳	flag_india	flag,india
        🇮🇴	flag_british_indian_ocean_territory	flag,british,indian,ocean,territory
        🇮🇶	flag_iraq	flag,iraq
        🇮🇷	flag_iran	flag,iran
        🇮🇸	flag_iceland	flag,iceland
        🇮🇹	flag_italy	flag,italy
        🇯🇪	flag_jersey	flag,jersey
        🇯🇲	flag_jamaica	flag,jamaica
        🇯🇴	flag_jordan	flag,jordan
        🇯🇵	flag_japan	flag,japan
        🇰🇪	flag_kenya	flag,kenya
        🇰🇬	flag_kyrgyzstan	flag,kyrgyzstan
        🇰🇭	flag_cambodia	flag,cambodia
        🇰🇮	flag_kiribati	flag,kiribati
        🇰🇲	flag_comoros	flag,comoros
        🇰🇳	flag_st_kitts_and_nevis	flag,st,kitts,and,nevis
        🇰🇵	flag_north_korea	flag,north,korea
        🇰🇷	flag_south_korea	flag,south,korea
        🇰🇼	flag_kuwait	flag,kuwait
        🇰🇾	flag_cayman_islands	flag,cayman,islands
        🇰🇿	flag_kazakhstan	flag,kazakhstan
        🇱🇦	flag_laos	flag,laos
        🇱🇧	flag_lebanon	flag,lebanon
        🇱🇨	flag_st_lucia	flag,st,lucia
        🇱🇮	flag_liechtenstein	flag,liechtenstein
        🇱🇰	flag_sri_lanka	flag,sri,lanka
        🇱🇷	flag_liberia	flag,liberia
        🇱🇸	flag_lesotho	flag,lesotho
        🇱🇹	flag_lithuania	flag,lithuania
        🇱🇺	flag_luxembourg	flag,luxembourg
        🇱🇻	flag_latvia	flag,latvia
        🇱🇾	flag_libya	flag,libya
        🇲🇦	flag_morocco	flag,morocco
        🇲🇨	flag_monaco	flag,monaco
        🇲🇩	flag_moldova	flag,moldova
        🇲🇪	flag_montenegro	flag,montenegro
        🇲🇫	flag_st_martin	flag,st,martin
        🇲🇬	flag_madagascar	flag,madagascar
        🇲🇭	flag_marshall_islands	flag,marshall,islands
        🇲🇰	flag_north_macedonia	flag,north,macedonia
        🇲🇱	flag_mali	flag,mali
        🇲🇲	flag_myanmar_burma	flag,myanmar,burma
        🇲🇳	flag_mongolia	flag,mongolia
        🇲🇴	flag_macao_sar_china	flag,macao,sar,china
        🇲🇵	flag_northern_mariana_islands	flag,northern,mariana,islands
        🇲🇶	flag_martinique	flag,martinique
        🇲🇷	flag_mauritania	flag,mauritania
        🇲🇸	flag_montserrat	flag,montserrat
        🇲🇹	flag_malta	flag,malta
        🇲🇺	flag_mauritius	flag,mauritius
        🇲🇻	flag_maldives	flag,maldives
        🇲🇼	flag_malawi	flag,malawi
        🇲🇽	flag_mexico	flag,mexico
        🇲🇾	flag_malaysia	flag,malaysia
        🇲🇿	flag_mozambique	flag,mozambique
        🇳🇦	flag_namibia	flag,namibia
        🇳🇨	flag_new_caledonia	flag,new,caledonia
        🇳🇪	flag_niger	flag,niger
        🇳🇫	flag_norfolk_island	flag,norfolk,island
        🇳🇬	flag_nigeria	flag,nigeria
        🇳🇮	flag_nicaragua	flag,nicaragua
        🇳🇱	flag_netherlands	flag,netherlands
        🇳🇴	flag_norway	flag,norway
        🇳🇵	flag_nepal	flag,nepal
        🇳🇷	flag_nauru	flag,nauru
        🇳🇺	flag_niue	flag,niue
        🇳🇿	flag_new_zealand	flag,new,zealand
        🇴🇲	flag_oman	flag,oman
        🇵🇦	flag_panama	flag,panama
        🇵🇪	flag_peru	flag,peru
        🇵🇫	flag_french_polynesia	flag,french,polynesia
        🇵🇬	flag_papua_new_guinea	flag,papua,new,guinea
        🇵🇭	flag_philippines	flag,philippines
        🇵🇰	flag_pakistan	flag,pakistan
        🇵🇱	flag_poland	flag,poland
        🇵🇲	flag_st_pierre_and_miquelon	flag,st,pierre,and,miquelon
        🇵🇳	flag_pitcairn_islands	flag,pitcairn,islands
        🇵🇷	flag_puerto_rico	flag,puerto,rico
        🇵🇸	flag_palestinian_territories	flag,palestinian,territories
        🇵🇹	flag_portugal	flag,portugal
        🇵🇼	flag_palau	flag,palau
        🇵🇾	flag_paraguay	flag,paraguay
        🇶🇦	flag_qatar	flag,qatar
        🇷🇪	flag_r_union	flag,r,union
        🇷🇴	flag_romania	flag,romania
        🇷🇸	flag_serbia	flag,serbia
        🇷🇺	flag_russia	flag,russia
        🇷🇼	flag_rwanda	flag,rwanda
        🇸🇦	flag_saudi_arabia	flag,saudi,arabia
        🇸🇧	flag_solomon_islands	flag,solomon,islands
        🇸🇨	flag_seychelles	flag,seychelles
        🇸🇩	flag_sudan	flag,sudan
        🇸🇪	flag_sweden	flag,sweden
        🇸🇬	flag_singapore	flag,singapore
        🇸🇭	flag_st_helena	flag,st,helena
        🇸🇮	flag_slovenia	flag,slovenia
        🇸🇯	flag_svalbard_and_jan_mayen	flag,svalbard,and,jan,mayen
        🇸🇰	flag_slovakia	flag,slovakia
        🇸🇱	flag_sierra_leone	flag,sierra,leone
        🇸🇲	flag_san_marino	flag,san,marino
        🇸🇳	flag_senegal	flag,senegal
        🇸🇴	flag_somalia	flag,somalia
        🇸🇷	flag_suriname	flag,suriname
        🇸🇸	flag_south_sudan	flag,south,sudan
        🇸🇹	flag_s_o_tom_and_pr_ncipe	flag,s,o,tom,and,pr,ncipe
        🇸🇻	flag_el_salvador	flag,el,salvador
        🇸🇽	flag_sint_maarten	flag,sint,maarten
        🇸🇾	flag_syria	flag,syria
        🇸🇿	flag_eswatini	flag,eswatini
        🇹🇦	flag_tristan_da_cunha	flag,tristan,da,cunha
        🇹🇨	flag_turks_and_caicos_islands	flag,turks,and,caicos,islands
        🇹🇩	flag_chad	flag,chad
        🇹🇫	flag_french_southern_territories	flag,french,southern,territories
        🇹🇬	flag_togo	flag,togo
        🇹🇭	flag_thailand	flag,thailand
        🇹🇯	flag_tajikistan	flag,tajikistan
        🇹🇰	flag_tokelau	flag,tokelau
        🇹🇱	flag_timor_leste	flag,timor,leste
        🇹🇲	flag_turkmenistan	flag,turkmenistan
        🇹🇳	flag_tunisia	flag,tunisia
        🇹🇴	flag_tonga	flag,tonga
        🇹🇷	flag_t_rkiye	flag,t,rkiye
        🇹🇹	flag_trinidad_and_tobago	flag,trinidad,and,tobago
        🇹🇻	flag_tuvalu	flag,tuvalu
        🇹🇼	flag_taiwan	flag,taiwan
        🇹🇿	flag_tanzania	flag,tanzania
        🇺🇦	flag_ukraine	flag,ukraine
        🇺🇬	flag_uganda	flag,uganda
        🇺🇲	flag_u_s_outlying_islands	flag,u,s,outlying,islands
        🇺🇳	flag_united_nations	flag,united,nations
        🇺🇸	flag_united_states	flag,united,states
        🇺🇾	flag_uruguay	flag,uruguay
        🇺🇿	flag_uzbekistan	flag,uzbekistan
        🇻🇦	flag_vatican_city	flag,vatican,city
        🇻🇨	flag_st_vincent_and_grenadines	flag,st,vincent,and,grenadines
        🇻🇪	flag_venezuela	flag,venezuela
        🇻🇬	flag_british_virgin_islands	flag,british,virgin,islands
        🇻🇮	flag_u_s_virgin_islands	flag,u,s,virgin,islands
        🇻🇳	flag_vietnam	flag,vietnam
        🇻🇺	flag_vanuatu	flag,vanuatu
        🇼🇫	flag_wallis_and_futuna	flag,wallis,and,futuna
        🇼🇸	flag_samoa	flag,samoa
        🇽🇰	flag_kosovo	flag,kosovo
        🇾🇪	flag_yemen	flag,yemen
        🇾🇹	flag_mayotte	flag,mayotte
        🇿🇦	flag_south_africa	flag,south,africa
        🇿🇲	flag_zambia	flag,zambia
        🇿🇼	flag_zimbabwe	flag,zimbabwe
        🏴󠁧󠁢󠁥󠁮󠁧󠁿	flag_england	flag,england
        🏴󠁧󠁢󠁳󠁣󠁴󠁿	flag_scotland	flag,scotland
        🏴󠁧󠁢󠁷󠁬󠁳󠁿	flag_wales	flag,wales
        """
}
